name: release

on:
  push:
  workflow_dispatch:
    inputs:
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: goreleaser/goreleaser-action@v4
        if: ${{ success() && !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --clean --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload linux arm64
        uses: actions/upload-artifact@v3
        if: ${{ success() && !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: linux_arm64
          retention-days: 10
          path: |
            dist/qqwry_Linux_arm64.tar.gz
      - name: Upload linux x86_64
        uses: actions/upload-artifact@v3
        if: ${{ success() && !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: linux_x86_64
          retention-days: 10
          path: |
            dist/qqwry_Linux_x86_64.tar.gz
      - name: Upload windows x86_64
        uses: actions/upload-artifact@v3
        if: ${{ success() && !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: windows_x86_64
          retention-days: 10
          path: |
            dist/qqwry_Windows_x86_64.zip